lanuage: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=pep8
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=pep8
  - env: TARGET=mypy
sudo: required
services:
 - docker
install:
 - true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: LW8gBbuZXiMH+IBMD4kVoEt1qUXCOZTsn9QKgX4s4Ta79dBSSaAjZXTAlVZs3JCAjrQ53erLrffsJezwLCrSFRTHHlyHSdiDmomdvHTfwzfZsShv8ZhbN3V8LAGG812ZIVMzOf8IWwodWxlJWK9GvWcPSWCHXUnXUUQ+/kCCHyE=
  on:
    tags: true
    repo: ska-sa/meqtrees-cattery
